export interface AIAgent {
  id: string;
  name: string;
  role: string;
  avatar: string;
  description: string;
  capabilities: string[];
  tools: string[];
}

export const AI_TEAM: AIAgent[] = [
  { 
    id: 'scoping', 
    name: 'Alice Scopes', 
    role: 'Scoping & Structuring Agent', 
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    description: 'Alice specializes in the crucial first step of any consulting engagement: problem definition. She interviews stakeholders, identifies core objectives, and establishes the boundaries of the engagement to ensure the team solves the right problem.',
    capabilities: ['Stakeholder Interview Simulation', 'Objective Alignment', 'Scope Definition', 'Risk Identification'],
    tools: ['OpenAI GPT-4o', 'LangChain', 'Contextual Memory']
  },
  { 
    id: 'issue_tree', 
    name: 'Marcus Tree', 
    role: 'Issue Tree Refinement Agent', 
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    description: 'Marcus is an expert in McKinsey-style logical structuring. He takes the defined scope and breaks it down into Mutually Exclusive, Collectively Exhaustive (MECE) sub-questions, forming the architectural backbone of the entire analysis.',
    capabilities: ['MECE Logic Trees', 'Hypothesis Generation', 'Driver Trees', 'Prioritization Matrices'],
    tools: ['Anthropic Claude 3.5 Sonnet', 'Graph Databases', 'Pinecone Vector DB']
  },
  { 
    id: 'research', 
    name: 'Elena Data', 
    role: 'Research & Data Extraction Agent', 
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    description: 'Elena is a relentless researcher. She connects to all integrated data sources (Shopify, Meta Ads, Google Analytics, internal PDFs) to extract the raw evidence required to prove or disprove the hypotheses generated by Marcus.',
    capabilities: ['Multi-Source Data Extraction', 'Semantic Search', 'Document Parsing', 'API Orchestration'],
    tools: ['Supabase Edge Functions', 'Pinecone Vector DB', 'Vercel AI SDK', 'Playwright Scraping']
  },
  { 
    id: 'analysis', 
    name: 'David Quant', 
    role: 'Quantitative Analysis Agent', 
    avatar: 'https://randomuser.me/api/portraits/men/46.jpg',
    description: 'David is a former investment banker turned AI. He excels at crunching the numbers Elena retrieves, performing cohort analyses, calculating LTV/CAC ratios, and identifying statistically significant trends in the data.',
    capabilities: ['Cohort Analysis', 'Financial Modeling', 'Statistical Significance Testing', 'Unit Economics'],
    tools: ['Python Data Stack (Pandas/NumPy)', 'PostgreSQL Analytical Functions', 'OpenAI Advanced Data Analysis']
  },
  { 
    id: 'synthesis', 
    name: 'Sarah Slides', 
    role: 'Synthesis & Presentation Agent', 
    avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    description: 'Sarah specializes in the Pyramid Principle. She takes David’s raw analysis and Elena’s findings, distilling them into a compelling narrative with a governing thought, key arguments, and supporting evidence.',
    capabilities: ['Pyramid Principle Synthesis', 'Executive Summary Generation', 'Slide Deck Outlining', 'Data Visualization Specs'],
    tools: ['Anthropic Claude 3.5 Sonnet', 'PptxGenJS', 'Markdown Mapping']
  },
  { 
    id: 'qa', 
    name: 'Victor Critique', 
    role: 'QA & Red-Team Agent', 
    avatar: 'https://randomuser.me/api/portraits/men/85.jpg',
    description: 'Victor is the ultimate skeptic. Before any deliverable reaches the client, Victor reviews the logic, checks the math, and searches for logical fallacies or missing evidence to ensure bulletproof quality.',
    capabilities: ['Logical Fallacy Detection', 'Math Verification', 'Formatting Compliance', 'Tone Analysis'],
    tools: ['OpenAI GPT-4o', 'Rule-Based Heuristics', 'Cross-Validation Prompting']
  },
  { 
    id: 'autofix', 
    name: 'Maya Fixer', 
    role: 'Auto-Fix Implementation Agent', 
    avatar: 'https://randomuser.me/api/portraits/women/33.jpg',
    description: 'Maya is the swift executor. When Victor identifies an issue, Maya immediately drafts the correction—whether it’s fixing a broken formula or rewriting an unsupported claim—saving hours of manual revision.',
    capabilities: ['Automated Revisions', 'Code/Formula Corrections', 'Content Patching', 'Version Control Integration'],
    tools: ['Vercel AI SDK (Tool Calling)', 'AST Parsing', 'Diff Generation']
  },
];
